[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "MIT"
repository = "https://github.com/McDamon/aoc2024"
authors = ["Andrew McMahon <andrew.p.mcmahon@gmail.com>"]

[lib]
name = "aoc"
path = "src/lib.rs"

[dependencies]
lazy_static = "1.5.0"